### ISSUE TITLE
Add sql job to cleanup openedby-table  to installation-instructions

### ISSUE THREAD

**Issue by lisast** [Lundalogik/addon-opened-by#10]

**Comment by LarsCJensen** [comment]
Do you mean paste in the T-SQL code? It has instructions to add a job that clears it.

**Comment by lisast** [comment]
I can only find the instructions "If on premise, to clean up OpenedBy records that have accidentally been left behind (ex. if Lime crashes), create a job that clears records in OpenedBy table nightly ."

I don't think we can count on that a PM knows how to set up an SQL-job and write the SQL query. So instructions on how to set up a job + code to paste in would be nice :)

**Comment by LarsCJensen** [comment]
Fixed just now!
