### ISSUE TITLE
SQL/agent_job: Remove schedule_id

### ISSUE THREAD

**Issue by lisast** [Lundalogik/addon-opened-by#17]
Remove schedule_id from agent_job (this will create a new schedule)

**Comment by LarsCJensen** [comment]
You mean clearing this: https://github.com/Lundalogik/addon-opened-by/blob/a0cea4bb2ca523f7b208cf90ccbddd8f66bdb40c/legacy/lip/sql/agent_job.sql#L57

**Comment by lisast** [comment]
@LarsCJensen Yes! The comma on the row above needs to be removed as well.

**Comment by LarsCJensen** [comment]
Hmm, should it perhaps be just an empty NVARCHAR?

**Comment by LarsCJensen** [comment]
Nevermind! That's an output.
