### ISSUE TITLE
Nya poster

### ISSUE THREAD

**Issue by EmmaEkstrom** [Lundalogik/addon-opened-by#8]
Vi har märkt att funktionaliteten inte funkar på nya poster. Se detta scenario:

1.	Jag skapar en ny historiknotering, skriver in min information på den och sparar den UTAN att stänga den. Då har OpenedBy registrerat att en historikpost är öppen med post-id:t stämmer inte eftersom det inte fanns när jag öppnade kortet (eftersom det är nytt). Post-id:t kommer ju först när jag sparar kortet och har jag redan kortet öppet så hamnar detta alltså inte i OpenedBy.
2.	En annan användare ser min historiknotering efter att jag sparat den (men jag har fortfarande kortet öppet). Då får denna person inte någon notis om att jag har kortet öppet redan.

Om man skapar en nya post gäller det alltså att man stänger den och öppnar den igen för att det ska fungera som tänkt. Jag tror dessa fall är väldigt sällsynta eftersom det är liten sannolikhet att någon öppnar ett kort som någon annan precis har skapat och dessutom tror jag de flesta gör allt de ska på kortet och sen kör de ”Spara och stäng”. Men kunden upplever ändå att det här är ett litet hål i funktionaliteten och undrar om vi kan täppa till det.

Ser ni någon enkel lösning på hur vi kan fixa detta? Jag tänker mig att vi borde kunna lägga in en kodsnutt i aftersave som lägger till raden med rätt post-id i openedby-tabellen (detta bör vi bara göra om posten är ny eftersom att det bara är då som id:t inte stämmer). Skulle vi kunna fixa till detta?

**Comment by LarsCJensen** [comment]
Vi skulle kunna fixa det, men det hade haft negativ påverkan på prestandan eftersom kortet måste sparas vid öppning. Jag rekommenderar inte att man gör så, men om kunden ändå vill göra det blir det en anpassning av kundens lösning, inte i addonet som jag ser det.
