### ISSUE TITLE
Opened-by posts doesn't get deleted when closing ticket

### ISSUE THREAD

**Issue by claudiaardelean** [Lundalogik/addon-opened-by#9]
There seems to be a bug where the opened-by posts doesn't get deleted, even though the ticket is closed "the right way" (i.e. the system does not crash). The ticket is closed either by "Save and close", "Esc" or "Cross". We can't find any connection to when this is happening exactly.

**Comment by LarsCJensen** [comment]
There are some glitches in the handling of certain events, but not the three you describe. I guess you can't repeat the issue?

**Comment by claudiaardelean** [comment]
No unfortunately not. My customer has not been able to find any connection for when this happens, but says it has happened more recently last week/s.

**Comment by LarsCJensen** [comment]
I tried a few different scenarios. I could repeat the issue if I opened a couple of records and then closed the first ones I opened using middle mouse click or cross through the taskbar. Only the last opened triggered beforeClose event when closed that way. 

I could however not repeat it using save and close, escape or cross. Have you heard anything else from customer?

**Comment by claudiaardelean** [comment]
Okay, no I havn't heard anything new yet. I can ask them how they are closing the records.

**Comment by LarsCJensen** [comment]
I think this has been found an solved, but not through openedby itself. You need to change some of the "general" VBA code. I've written an example in the documentation and will try it in Sublime.
